on:
  push:
    branches: [main, develop, 'release/**']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  spotbugs-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven repo
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run SpotBugs (XML)
        run: mvn clean verify

      - name: Install tools for XSLT conversion
        run: sudo apt-get update && sudo apt-get install -y xsltproc unzip

      - name: Extract SpotBugs XSLT from local cache
        run: |
          # find the spotbugs engine JAR in the local Maven repo
          JAR=$(find ~/.m2/repository/com/github/spotbugs/spotbugs/ -name "spotbugs-*.jar" | head -n1)
          echo "Using XSL from $JAR"
          unzip -p "$JAR" etc/default.xsl > spotbugs.xsl

      - name: Transform XML → HTML
        run: xsltproc spotbugs.xsl target/spotbugs.xml > target/spotbugs.html

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: |
            target/spotbugs.xml
            target/spotbugs.html